### ISSUE TITLE
Cannot Connect PrestaShop to Printful 

### ISSUE THREAD

**Issue by Boltz001** [printful/prestashop-module#5]
When I try to connect my shop to Printful it keeps popping up with error 503 service temporarily unavailable. 
![image](https://user-images.githubusercontent.com/65959843/142240126-b4105091-3b02-4396-9af9-40fcbd8db397.png)

Version: 
Printful latest release 
Prestashop 1.7.8.1 

I think it's the outdated printful plugin that may be the issue. 
I've contacted dev team but had no reply within a week so this is my last hope

**Comment by rkistaps** [comment]
Hello, there seems to be a WordPress site on that domain. Also, https://shop.djsteamzy.com/api is now throwing the 500 server error. Have you moved away from Prestashop integration?

The reason that is visible in the screenshot is coming from your website. It means that we tried to communicate with it at received 503. I suggest checking server error logs for more insights on that.
