### ISSUE TITLE
When Prestashop (version 1.7.8.6) is in multistore mode, only the FIRST store connected to Printful appears to be connected at the Prestashop console.

### ISSUE THREAD

**Issue by krisgholson** [printful/prestashop-module#7]
Prestashop revamped the multistore mode functionality in version 1.7.8 (https://build.prestashop.com/news/multistore-news-in-1.7.8/). The currently Printful PrestaShop module does not work smoothly when the PrestaShop is in multistore mode. Currently, only the FIRST store connected to Printful appears to be connected from the PrestaShop dashboard.

An error is received when attempting to connect any store (after the first one) using the Printful Prestashop module ...
![prestashop_0](https://user-images.githubusercontent.com/2716657/176957167-b66e0ae2-c632-4a32-ae46-e061a46db105.png)

A PrestaShop store IS correctly created in Printful ...
![prestashop_1](https://user-images.githubusercontent.com/2716657/176957336-e4adb273-c904-439c-929d-8ca532c4704c.png)

![prestashop_2](https://user-images.githubusercontent.com/2716657/176957386-5a74b408-1064-4c3e-acca-a09c96590336.png)

But in PrestaShop, all stores (other than the first one connected) appear as if they are NOT connected to Printful ...
![prestashop_3](https://user-images.githubusercontent.com/2716657/176957409-99aa304c-51db-4a7e-b1e5-c3a0d7a724eb.png)

The first store that was connected from PrestaShop to Printful using the Printful PrestaShop module DOES appear to be properly connected.
![prestashop_4](https://user-images.githubusercontent.com/2716657/176957482-5112b369-c048-4bc3-abb4-b7872523a17f.png)

Desired resolution:
* No error when the Prestashop/Printful user connects Prestashop to Printful for all stores when Prestashop is in multistore mode.
* The Printful module in Prestashop correctly shows the Printful dashboard / orders tab for all PrestaShop stores that were connected to Printful.

**Comment by krisgholson** [comment]
This is the data available from my PrestaShop instance in the information tab:

```
info_outline Configuration information
This information must be provided when you report an issue on GitHub or on the forum.

info_outline Server information
Server information: Linux #1 SMP Sat Mar 12 00:44:41 UTC 2022 x86_64

Server software version: Apache/2.4.38 (Debian)

PHP version: 7.3.31-1~deb10u1

Memory limit: 256M

Max execution time: 30

Upload Max File size: 128M

info_outline Database information
MySQL version: 5.7.12

MySQL server: [my url]

MySQL name: [my db name]

MySQL user: [my db user]

Tables prefix: ps_

MySQL engine: InnoDB

MySQL driver: DbPDO

info_outline List of overrides
info_outline Store information
PrestaShop version: 1.7.8.6

Shop URL: http://upcycle.swaggy.shop/

Shop path: /var/www/prestashop-1.7.8.6

Current theme in use: classic

info_outline Mail configuration
Mail method: You are using your own SMTP parameters.

SMTP server: smtp.gmail.com

SMTP username: Defined

SMTP password: Defined

Encryption: tls

SMTP port: 587

info_outline Your information
Your web browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

info_outline Check your configuration
Required parameters: OK

Optional parameters: OK
```

**Comment by rkistaps** [comment]
Hello. Our plugin indeed does not fully support the multistore functionality in the Prestashop. This feedback is registered as a feature request. Thanks
